### ISSUE TITLE
Default example fails when on Production Clerk configuration

### ISSUE THREAD

**Issue by dbredvick** [clerkinc/clerk-chrome-extension-starter#2] opened 2023-06-03 22:42 UTC
I have built out a Chrome extension using this as a starter, but am running into issues as I try to publish the extension to the Chrome App Store.

I have migrated my clerk.dev instance to production, setting up CNAME records for the underlying Clerk endpoints:
- accounts.autopitch.ai
- clerk.autopitch.ai

Logging in works perfectly, but when the SDK tries to refresh session tokens, it starts erroring, e.g. https://clerk.autopitch.ai/v1/client/sessions/sess_2QhwYFJGCL644Q9qszdT58uuYFE/tokens?_clerk_js_version=4.42.0

This request errors out with the response:
```JSON
{"errors":[{"message":"Invalid HTTP Origin header","long_message":"The Request HTTP Origin header must be equal to or a subdomain of the requesting URL.","code":"origin_invalid"}],"clerk_trace_id":"3359086daee909e59c20ad68f55094a6"}
```

The origin of the request, since it is a chrome extension, is of the format `chrome-extension://uuid`.

While there was previously ways to address this in manifest V3 extensions, there seems to be some issue with it now: https://bugs.chromium.org/p/chromium/issues/detail?id=966223

I unfortunately cannot add `chrome-extension://uuid` as a subdomain in the Clerk UI, so I'm currently looking for workarounds to see if I can fix this at the code level.

Would love if y'all had any guidance here so that we can update the README with a `going to production` section.

**Comment by dbredvick** [comment] 2023-06-05 03:17
Okay I've got a working solution here using the Declarative Network Request API. It's a bit complicated to get working correctly.

[These examples](https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/api-samples/declarativeNetRequest) are great to reference.

Add the following permissions to your `manifest.json`

```
"declarativeNetRequestWithHostAccess",
 "declarativeNetRequest",
 "declarativeNetRequestFeedback"
```

Add a mapping for the rules in `manifest.json`

```
"declarative_net_request": {
    "rule_resources": [
      {
        "id": "modify-origin",
        "enabled": true,
        "path": "modify-origin.json"
      }
    ]
  }
```

modify-origin.json:

```json
[
  {
    "id": 1,
    "priority": 1,
    "action": {
      "type": "modifyHeaders",
      "requestHeaders": [
        {
          "header": "origin",
          "operation": "set",
          "value": "https://yourdomainhere.com"
        }
      ]
    },
    "condition": {
      "urlFilter": "|*?_clerk_js_version=4.42.0",
      "resourceTypes": [
        "main_frame",
        "sub_frame",
        "stylesheet",
        "script",
        "image",
        "font",
        "object",
        "xmlhttprequest",
        "ping",
        "csp_report",
        "media",
        "websocket",
        "other"
      ]
    }
  }
]
```

Including all resource types is probably aggressive, we could scope that down.

Since all Clerk API calls include the version number, the URL matcher will match every request, regardless of the domain. We could also make more specific rules that target each CNAME that we set up for production.

I'll start a PR with these changes tomorrow.

**Comment by SokratisVidros** [comment] 2023-06-05 09:46
Hey @dbredvick can you please try adding your chrome-extension://uuid to your instance allowed origins via 

```curl  -X PATCH https://api.clerk.com/v1/instance \
      -H "Authorization: Bearer sk_secret_key" \
      -H "Content-type: application/json" \
      -d '{"allowed_origins": ["chrome-extension://extension_id_goes_here"]}'```
      
as described [here](https://github.com/clerkinc/javascript/tree/main/packages/chrome-extension#clerk-settings)?

**Comment by dimkl** [comment] 2023-06-06 10:21
Hey @dbredvick , did the above solution fix your issue? 
If so, could you please close this issue?

**Comment by dbredvick** [comment] 2023-06-07 01:20
@dimkl Unfortunately I am still seeing the error after adding my chrome-extension via the curl.

I also tried using the docs endpoint to PATCH this same content in case my curl was not correct: 
<img width="491" alt="CleanShot 2023-06-06 at 20 18 49@2x" src="https://github.com/clerkinc/clerk-chrome-extension-starter/assets/10567141/14b01543-efe8-44cf-b70d-727c3ceabb83">

I am strangely still seeing the error if I stop overriding the origin header:
```
{"errors":[{"message":"Invalid HTTP Origin header","long_message":"The Request HTTP Origin header must be equal to or a subdomain of the requesting URL.","code":"origin_invalid"}],"clerk_trace_id":"3359086daee909e59c20ad68f55094a6"}
```

**Comment by SokratisVidros** [comment] 2023-06-09 07:50
@dbredvick Are you executing Clerk frontend API requests from the extension popup or from its service worker?

**Comment by yoimnik** [comment] 2023-06-10 07:06
@SokratisVidros @dimkl howdy

@dbredvick thanks for making a github issue on this problem. we're going to try your work around solution with Declarative Network Request API.

with that said tho -- we are having a problem with signing into clerk via our chrome extension (ie. Standalone, not Web SSO)

![Screenshot_2023-06-09_at_6 43 12_PM](https://github.com/clerkinc/clerk-chrome-extension-starter/assets/12193963/5c72785d-d825-4fab-9d31-bedea17d4a2b)

we ran the PATCH curl command on the instance settings to set `allowed_origins` to the `chrome-extension://identifier` and got a 204 response, but we still get the same issue:

<img width="781" alt="image" src="https://github.com/clerkinc/clerk-chrome-extension-starter/assets/12193963/5bb7d4b2-ec14-442b-b763-9f6784be6c2c">

any help would be great.

gammagang.com is our domain on clerk.

**Comment by SokratisVidros** [comment] 2023-06-12 14:43
Team, we've spotted a bug for chrome extensions in our APIs. We've added a temporary patch to unblock you while working on a proper fix. Let me know if the issue is resolved.

**Comment by yolotrader** [comment] 2023-06-12 18:32
Hi there,

I tried to use the latest Chrome extension library and it triggers the following error, since Chrome now blocks remote scripts completely:
![Screenshot 2023-06-10 at 12 43 55 PM](https://github.com/clerkinc/clerk-chrome-extension-starter/assets/136374021/f221d7c8-97c0-41d3-acaf-8e6f1767432d)

The highest version and its dependencies that don't cause this are:
![Screenshot 2023-06-12 at 11 28 56 AM](https://github.com/clerkinc/clerk-chrome-extension-starter/assets/136374021/ec5728b5-d602-4d3d-ba87-e9049418a56a)

Is this a known issue?

Thanks for helping out!

**Comment by SokratisVidros** [comment] 2023-06-21 10:47
@yolotrader does the issue persist in the latest stable version of `@clerk/chrome-extension`?

**Comment by SokratisVidros** [comment] 2023-06-23 19:17
> Team, we've spotted a bug for chrome extensions in our APIs. We've added a temporary patch to unblock you while working on a proper fix. Let me know if the issue is resolved.

The fix is now live. I am closing this issue.

**Closed by SokratisVidros** 2023-06-23 19:17 UTC
Labels: chrome-extension-issue

**Comment by jellohouse** [comment] 2023-11-08 17:32
Getting this error too now with latest "@clerk/chrome-extension": "0.4.13"

```
clerk.mjs:98 Refused to load the script 'https://clerk.XXXXXX.XXX/cloudflare/turnstile/v0/api.js?render=explicit&_clerk_js_version=4.64.2' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```
